### ISSUE TITLE
Theme looks strange on Rocknix

### ISSUE THREAD

**Issue by 0kti** [symbuzzer/es-theme-knulli#2] opened 2024-11-01 17:52 UTC
Could you update fix theme for rocknix?
I've upload on x55 and theme looks like there is some errors, like no video snaps or image screens

**Comment by symbuzzer** [comment] 2024-11-01 18:11
I will try to fix but I need video preview sir. Can you share with me please? @0kti

**Comment by 0kti** [comment] 2024-11-01 18:20
sure
https://youtube.com/shorts/TCvxcLsCbok?si=Vtn3bkoJrCqZYcd1

**Comment by symbuzzer** [comment] 2024-11-01 18:22
@0kti please try 1.4.0

**Comment by 0kti** [comment] 2024-11-01 18:24
if it's from today, it's already uploaded but I can't change settings from 1.3.2 to anything

________________________________
Od: Ali Beyaz ***@***.***>
Wysłane: piątek, 1 listopada 2024 19:23
Do: symbuzzer/es-theme-knulli ***@***.***>
DW: 0kti ***@***.***>; Mention ***@***.***>
Temat: Re: [symbuzzer/es-theme-knulli] Theme looks strange on Rocknix (Issue #2)


@0kti<https://github.com/0kti> please try 1.4.0

**Comment by symbuzzer** [comment] 2024-11-01 18:26
@0kti u cant change 1.3.2
please download and install 1.4.0 from there: https://github.com/symbuzzer/es-theme-knulli/releases/tag/v1.4.0

**Comment by 0kti** [comment] 2024-11-01 18:28
I did it, first I delete previous version from etc/emulationstation,
restarted rocknix,
downloaded 1.4.0 from github and uploaded again to rocknix,
but it still shows 1.3.2 on knulli settings

________________________________
Od: Ali Beyaz ***@***.***>
Wysłane: piątek, 1 listopada 2024 19:26
Do: symbuzzer/es-theme-knulli ***@***.***>
DW: 0kti ***@***.***>; Mention ***@***.***>
Temat: Re: [symbuzzer/es-theme-knulli] Theme looks strange on Rocknix (Issue #2)


@0kti<https://github.com/0kti> u cant change 1.3.2
please download and install 1.4.0 from there: https://github.com/symbuzzer/es-theme-knulli/releases/tag/v1.4.0

**Comment by 0kti** [comment] 2024-11-01 18:34
I've downloaded again, extracted and upload, now it shows 1.4.0 in settings, but this doesn't change anything

**Comment by symbuzzer** [comment] 2024-11-01 18:34
@0kti Sorry I cant reproduce your error. You should install 1.4.0 succesfully before. 
Also, problem is probably fixed on v1.4.0. Please see its changelog

**Comment by 0kti** [comment] 2024-11-01 18:36
I have R36S console with AmberELEC firmware.
There is everything ok, looks like rocknix have some issues, idk why

**Comment by symbuzzer** [comment] 2024-11-01 18:42
@0kti es-theme-knulli is originally created for anbernic h700 devices with roms has emulationstation frontend. h700 devices have small screens, generally 640x480. So it cant work with devices have bigger screens.

I tried to fix this compliant with latest 1.4.0 release. I hope u can install and test it

**Comment by 0kti** [comment] 2024-11-01 18:44
like I write before
1.4.0 on AmberElec is working fine, looks great
1.4.0 on Rocknix looks like on video i've send before
strange issue

________________________________
Od: Ali Beyaz ***@***.***>
Wysłane: piątek, 1 listopada 2024 19:43
Do: symbuzzer/es-theme-knulli ***@***.***>
DW: 0kti ***@***.***>; Mention ***@***.***>
Temat: Re: [symbuzzer/es-theme-knulli] Theme looks strange on Rocknix (Issue #2)


@0kti<https://github.com/0kti> es-theme-knulli is originally created for anbernic h700 devices with roms has emulationstation frontend. h700 devices have small screens, generally 640x480. So it cant work with devices have bigger screens.

I tried to fix this compliant with latest 1.4.0 release. I hope u can install and test it

**Comment by symbuzzer** [comment] 2024-11-01 18:49
please send video of 1.4.0 rocknix installed @0kti

**Comment by symbuzzer** [comment] 2024-11-15 15:53
@0kti any news sir?

**Comment by 0kti** [comment] 2024-11-15 17:02
I will upload now and I let you know :)

**Comment by 0kti** [comment] 2024-11-15 17:13
Strange, the same theme looks different on R36 (AmberElec firmware) and Powkiddy X55 (Rocknix firmware) and idk why, same settings, same knulli version 

https://ibb.co/JQGGmBv
https://ibb.co/YDHDRn4
https://ibb.co/0q1sgZS
https://ibb.co/1vxpxT9

**Comment by symbuzzer** [comment] 2024-11-15 19:14
sorry, es-theme-knulli is designed small screen devices.
also it is an es-de theme which is only compatible with dekstop oses
ı have no amberelec device to trying to fix issue. maybe u should try to set file permissions like other themes.

**Comment by 0kti** [comment] 2024-11-15 19:17
on AmberElec looks fine, problem is with Rocknix

**Comment by symbuzzer** [comment] 2024-11-15 19:36
so problem is from screen size probably

**Closed as not planned** 2024-11-25 08:07 UTC
